general:
  target_ip: "http://35.238.138.9/"
  threads: 50
  attack_duration: 300
  log_file: "logs/combined_logs/combined_attack.log"

run_hash: true
run_api: true

hash_collision:
  endpoint: "/wp-admin/admin-ajax.php"
  num_collisions: 1000
  base_string: "test_string"
  hash_algorithm: "md5"

api_abuse:
  endpoint: "/wp-json/wp/v2/posts"
  methods: ["GET", "POST", "PUT", "DELETE"]
  headers:
    User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
    Content-Type: "application/json"
  data_payloads:
    - {"title": "Attack Post 1", "content": "This is a test attack content"}
    - {"title": "Attack Post 2", "content": "This is a second test attack content"}

